@startuml class_diagram

skinparam linetype ortho
left to right direction
skinparam classArrowColor black
skinparam nodesep 120
skinparam ranksep 120

skinparam ClassDiagram {
    ArrowThickness 1
    ArrowColor black
    HorizontalSpacing 60
    VerticalSpacing 60
    ArrowFontSize 11
    ArrowFontColor black
    ArrowFontStyle plain
}

abstract class BaseGameEntity {
    {static} - next_ID: int
    - ID: int
    - position: Vector2D
    - environment: World

    + BaseGameEntity (x: float, y: float, world: World)
    {abstract} + update (delta_time: float) : None
    + get_position () : Vector2D
    + set_position (new_position: Vector2D) : None
    + get_ID () : int
    - set_ID () : int
}

class MovingEntity extends BaseGameEntity {
    - velocity: Vector2D
    - acceleration: Vector2D
    - angular_acceleration: float
    - orientation: float
    - rotation: float
    - mass: int
    - max_speed: float
    - max_acceleration: float
    - max_rotation: float
    - max_angular_acceleration: float
    - color: Color
    - state_machine: StateMachine

    + MovingEntity (x: float, y: float, world: World, mass: float, max_speed: float, max_acceleration: float, max_rotation: float, max_angular_acceleration: float, color_name: str)
    + draw (screen: Surface) : None
    + apply_steering (steering: SteeringOutput, delta_time: float) : None
    + change_color (color_name: str) : None
    + change_state (new_state: State) : None
    + get_direction () : Vector2D
    + get_velocity () : Vector2D
    + get_acceleration () : Vector2D
    + get_angular_acceleration () : float
    + get_orientation () : float
    + get_rotation () : float
    + get_mass () : float
    + get_max_speed () : float
    + get_max_acceleration () : float
    + get_max_rotation () : float
    + get_max_angular_acceleration () : float
    + get_color () : Color
    + set_velocity (value: Vector2D) : None
    + set_acceleration (value: Vector2D) : None
    + set_angular_acceleration (value: float) : None
    + set_orientation (value: float) : None
    + set_rotation (value: float) : None
    + set_mass (value: float) : None
    + set_max_speed (value: float) : None
    + set_max_acceleration (value: float) : None
    + set_max_rotation (value: float) : None
    + set_max_angular_acceleration (value: float) : None
    + set_color (value: str | Color) : None
    - limit_entity () : None
    - apply_force (force: Vector2D) : None
}

class World {
    - domain: Surface
    - width: int
    - height: int
    - entities: list[BaseGameEntity]

    + World (screen: Surface)
    + update (delta_time: float) : None
    + add_entity (entity: BaseGameEntity) : None
    + remove_entity (entity: BaseGameEntity) : None
}

class SteeringOutput {
    - linear: Vector2D
    - angular: float

    + SteeringOutput ()
    + get_linear () : Vector2D
    + get_angular () : float
    + set_linear (value: Vector2D) : None
    + set_angular (value: Vector2D) : None
}

class BehaviorAndWeight {
    - state: State
    - weight: float

    + BehaviorAndWeight (state: State, weight: float)
    + get_state () : State
    + get_weight () : float
    + set_state (value: State) : None
    + set_weight (value: float) : None
}

class Collision {
    - position: Vector2D
    - normal: Vector2D

    + Collision ()
    + get_position () : Vector2D
    + get_normal () : Vector2D
    + set_position (value: Vector2D) : None
    + set_normal (value: Vector2D) : None
}

class StateMachine {
    - owner: MovingEntity
    - current_state: State
    - previous_state: State

    + StateMachine (owner: MovingEntity, start_state: State)
    + update (delta_time: float) : None
    + change_state (new_state: State) : None
    + revert_to_previous_state () : None
}

class InputController {
    - character: MovingEntity
    - target: MovingEntity
    - key_to_state: dict[Key, State]

    + InputController (character: MovingEntity, target: MovingEntity)
    + handle_event (event: Event) : None
}

class RadiusCalculator <<functor>> {
    - world: World
    - character_radius: float

    + RadiusCalculator (world: World, character_radius: float)
}

class SteeringTarget {
    - position: Vector2D
    - velocity: Vector2D
    - rotation: float
    - orientation: float

    + SteeringTarget (position: Vector2D, orientation: float)
    + get_position () : Vector2D
    + get_velocity () : Vector2D
    + get_rotation () : float
    + get_orientation () : float
    + set_position (value: Vector2D) : None
    + set_velocity (value: Vector2D) : None
    + set_orientation (value: float) : None
    + set_rotation (value: float) : None
}

abstract class State {
    - entity: MovingEntity

    - State (entity: MovingEntity)
    {abstract} + enter () : None
    {abstract} + exit () : None
    {abstract} + execute (delta_time: float) : None
    {abstract} + get_steering () : SteeringOutput
}

abstract class MultiTargetState extends State {
    - targets: list[MovingEntity]
    - threshold: float

    - MultiTargetState (entity: MovingEntity, threshold: float)
    + get_threshold () : float
    + set_threshold (value: float) :  None
}

abstract class SingleTargetState extends State {
    - target: MovingEntity

    - SingleTargetState (entity: MovingEntity, target: MovingEntity)
}

class Align extends SingleTargetState {
    - slow_radius: float
    - max_rotation: float
    - target_radius: float
    - time_to_target: float
    - max_angular_acceleration: float

    + Align (entity: MovingEntity, target: MovingEntity, slow_radius: float, target_radius: float, time_to_target: float, max_rotation: float, max_angular_acceleration: float)
}

class Face extends Align {
    + Align (entity: MovingEntity, target: MovingEntity, slow_radius: float, target_radius: float, time_to_target: float, max_rotation: float, max_angular_acceleration: float)
}

class Wander extends Face {
    - wander_rate: float
    - wander_offset: float
    - wander_radius: float
    - max_acceleration: float
    - wander_orientation: float

    + Wander (entity: MovingEntity, target: MovingEntity, slow_radius: float, target_radius: float, time_to_target: float, max_rotation: float, max_angular_acceleration: float, wander_offset: float, wander_radius: float, wander_rate: float, max_acceleration: float)
}

class Arrive extends SingleTargetState {
    - distance: float
    - slow_radius: float
    - direction: Vector2D
    - target_radius: float
    - time_to_target: float

    + Arrive (entity: MovingEntity, target: MovingEntity, slow_radius: float, target_radius: float, time_to_target: float)
}

class Attraction extends MultiTargetState {
    - max_acceleration: float
    - decay_coefficient: float

    + Attraction (entity: MovingEntity, threshold: float, decay_coefficient: float)
}

class BlendedSteering extends State {
    - max_rotation: float
    - max_acceleration: float
    - behaviors: list[BehaviorAndWeight]

    + BlendedSteering (entity: MovingEntity, behaviors: list[BehaviorAndWeight])
}

class Cohesion extends MultiTargetState {
    + Cohesion (entity: MovingEntity, threshold: float)
}

class Seek extends SingleTargetState {
    + Seek (entity: MovingEntity, target: MovingEntity)
}

class CollisionAvoidance extends Seek {
    - collision_ray: float
    - avoid_distance: float
    - collision_detector: CollisionDetector

    + CollisionAvoidance (entity: MovingEntity, target: MovingEntity, collision_ray: float, avoid_distance: float)
}

class Flee extends SingleTargetState {
    + Flee (entity: MovingEntity, target: MovingEntity)
}

class Evade extends Flee {
    - max_prediction: float

    + Evade (entity: MovingEntity, target: MovingEntity, max_prediction: float)
}

class MaintainRadius extends SingleTargetState {
    - tolerance: float
    - max_acceleration: float
    - radius_calculator: RadiusCalculator

    + MaintainRadius (entity: MovingEntity, leader: MovingEntity, radius_calculator: RadiusCalculator)
}

class PrioritySteering extends State {
    - groups: list[BlendedSteering]
    - epsilon: float

    + PrioritySteering (entity: MovingEntity, groups: list[BlendedSteering], epsilon: float)
}

class Pursue extends Seek {
    - max_prediction: float

    + Pursue (entity: MovingEntity, target: MovingEntity, max_prediction: float)
}

class Separation extends MultiTargetState {
    - max_acceleration: float
    - decay_coefficient: float

    + Separation (entity: MovingEntity, threshold: float, decay_coefficient: float)
}

class VelocityMatch extends MultiTargetState {
    - threshold: float
    - slow_radius: float
    - time_to_target: float

    + VelocityMatch (entity: MovingEntity, threshold: float, slow_radius: float, time_to_target: float)
}

class CollisionDetector {
    + CollisionDetector ()
    + get_collision (position: Vector2D, vector: Vector2D) : Collision
}

MovingEntity "1 owner" *-- "1 state_machine" StateMachine
World "1 environment" o-- "0..* entities" BaseGameEntity
State o--> "1 entity" MovingEntity
State ..> SteeringOutput: uses
SingleTargetState o--> "1 target" MovingEntity
MultiTargetState o--> "1..* targets" MovingEntity
BlendedSteering o--> "0..1 behaviors" BehaviorAndWeight
PrioritySteering o--> "0..1 groups" BlendedSteering
InputController o--> "1 entity" MovingEntity
InputController o--> "1 target" MovingEntity
CollisionAvoidance *--> "1 collision_detector" CollisionDetector
StateMachine o--> "1 current_state" State
StateMachine o--> "1 previous_state" State
MaintainRadius o--> "1 radius_calculator" RadiusCalculator
BehaviorAndWeight o--> "1 state" State
CollisionDetector ..> Collision: returns
CollisionAvoidance ..> Collision: uses
MultiTargetState ..> World: uses
InputController ..> State: uses
State ..> SteeringTarget: uses

@enduml